const data = {
  products: [
    { 
        _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', //679px x 829px
      price: 129,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 20,
      description: 'High Quality Shirt',
    },
    {
      _id: '2',
      name: 'Nike Sweat Pants',
      slug: 'nike-sweat-pants',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 130,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 20,
      description: 'High Quality Pants',
    },
    {
      _id: '3',  
      name: 'Adidas Slim Shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 50,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 50,
      description: 'Good Quality Shirt',
    },
    {
      _id: '4',  
      name: 'Adidas Slim Pants',
      slug: 'adidas-slim-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 139,
      countInStock: 200,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 200,
      description: 'High Quality Pants',
    },
  ],
};

export default data;
